### ISSUE TITLE
Pulumi up failure on subsequent tries due to Aurora version

### ISSUE THREAD

**Issue by greg-prospyr** [pulumi/pulumi-metabase#1]
### What happened?

Receive this error after running `pulumi up` once Metabase has already successfully deployed once: 

``* Failed to modify RDS Cluster (mb-prometabasemysql): InvalidParameterCombination: Cannot find upgrade target from 5.7.serverless_mysql_aurora.2.08.3 with requested version 5.7.mysql_aurora.2.07.1 for serverless engine mode.
      	status code: 400, request id: e2192228-d509-4d8b-b209-113ff5814e25``

### Steps to reproduce

Run `pulumi up` again after having a successful `pulumi up`

### Expected Behavior

I expect `pulumi up` to succeed

### Actual Behavior

Receive this error after running `pulumi up` once Metabase has already successfully deployed once: 

``* Failed to modify RDS Cluster (mb-prometabasemysql): InvalidParameterCombination: Cannot find upgrade target from 5.7.serverless_mysql_aurora.2.08.3 with requested version 5.7.mysql_aurora.2.07.1 for serverless engine mode.
      	status code: 400, request id: e2192228-d509-4d8b-b209-113ff5814e25``

### Output of `pulumi about`

Dependencies:
NAME                VERSION
@pulumi/aws         4.28.0
@pulumi/aws-native  0.19.0
@pulumi/awsx        0.30.0
@pulumi/command     0.2.0
@pulumi/github      4.9.0
@pulumi/metabase    0.0.2
@pulumi/pulumi      3.17.1
@pulumi/random      4.3.1
@pulumi/tls         4.1.0
mime                3.0.0
typescript          4.5.5
@types/mime         2.0.3
@types/node         14.17.33

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by greg-prospyr** [comment]
@zchase if I made a PR that includes the option to pass the Aurora version when configuring this module would you be able to merge that in?

**Comment by zchase** [comment]
@greg-prospyr Yeah we will gladly accept a PR and cut a release!

**Comment by zchase** [comment]
@greg-prospyr Looking into this I do have some questions about how useful you find exposing all the arguments of an RDS cluster instead of just the version. It is not out of the question to support all of [RDS Inputs](https://www.pulumi.com/registry/packages/aws/api-docs/rds/cluster/#inputs) and provide a set of defaults.

Regardless I have a version that exposes the Aurora version as an argument but I need to do some more testing to ensure it works as expected.

**Comment by greg-prospyr** [comment]
thanks for looking into this @zchase! Really appreciate! 🙏 For our use case, the reason we'd like to be able to configure the RDS cluster version is to stop the deploy issue we are having.

From a general perspective, I think the strategy of having sane defaults for RDS Inputs plus the ability to change them where necessary would be a great step forward and improve the overall usability of the module.

**Comment by zchase** [comment]
@greg-prospyr We just release version 0.0.3 which exposes `engineVersion` as an argument. Though the bug was related to a mismatch between the hardcoded version and what was being provisioned. I think you should be able to upgrade to 0.0.3 and be on your way! Let me know if you have any more issues or suggested features!

**Comment by greg-prospyr** [comment]
thank you so much @zchase ! Really appreciate your help here
